"""initialize project

Revision ID: 82837f0cea64
Revises: 
Create Date: 2024-09-22 00:00:56.780748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82837f0cea64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('second_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('language_code', sa.Text(), server_default='ru', nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='role'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_user_id'))
    )
    op.create_table('thread',
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_thread_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thread')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_thread_conversation_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    op.drop_table('user')
    # ### end Alembic commands ###
